name: Test

on:
  - push

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --strict-peer-dependencies
          pnpm install --global gulp prettier typescript

      - name: Set up environment variables
        run: |
          echo "PORT=4500" >> .env
          echo "JWT_SECRET=jwt_secret" >> .env

      - name: Run lint tests
        run: pnpm npm run lint --if-present
        
      - name: Run tests
        run: pnpm test
